### ISSUE TITLE
Update Details > Password results in error

### ISSUE THREAD

**Issue by Avitus27** [UCCNetworkingSociety/NetsocAdmin#2]
```
ErrorException in adLDAPUsers.php line 344:
ldap_modify(): Modify: No such object 
```

returned in cases when you update account password and press enter.

**Comment by TheJokersThief** [comment]
@Avitus27 This is because you're in a committee group within LDAP. Will work on generalising it but in the meantime, you can change your password via SSH :stuck_out_tongue:

**Comment by Avitus27** [comment]
Righto, thanks a million :+1:

**Comment by cahalane** [comment]
Should we leave this open just as a reminder? ^
