### ISSUE TITLE
Need check for folder permissions before beginning wordpress install

### ISSUE THREAD

**Issue by TheJokersThief** [UCCNetworkingSociety/NetsocAdmin#4]
Currently, the wordpress install requires 0775 permissions on the folder it's being installed in for www-data to have proper access. If this access doesn't exist, an error should be flagged.

(cc @colm2)

**Comment by cahalane** [comment]
Also, does it check for the folder existing/creates the folder if not exists?

**Comment by TheJokersThief** [comment]
@colm2 No, that would require it having 0775 permissions for the entire public_html folder at all times. This way, users can dictate which folders have those permissions as the globally recommended setting for folders is 0755.
